import assert from 'node:assert/strict';
import { readFile, writeFile } from 'node:fs/promises';
const source = await readFile(new URL('./assets/excel-export.js', import.meta.url), 'utf8');
const { buildRows, workbookBlob } = await import('data:text/javascript;base64,' + Buffer.from(source).toString('base64'));
const sessions = [{ supervisor: 'João & Ana', observer: 'José', region: 'São Paulo', start: 0, end: null, activities: [{ id: 'a', details: 'Detalhes com acentos: revisão & teste', description: '=1+1 <teste>', category: 'Gestão', demand: 'Imprevista' }, { id: 'b', description: 'Reunião', planned: true }], segments: [{ activityId: 'a', start: 0, end: 60000 }, { activityId: 'b', start: 60000, end: null }] }];
const rows = buildRows(sessions, 90000, () => 'Editada');
assert.equal(rows[0][6], 'Demanda');
assert.equal(rows[1][6], 'Imprevista');
assert.equal(rows[2][6], 'Planejada');
assert.equal(rows[1][9], 60);
assert.equal(rows[2][9], 30);
assert.equal(rows[1][11], 'Editada');
const bytes = new Uint8Array(await workbookBlob(rows).arrayBuffer());
assert.equal(new DataView(bytes.buffer).getUint32(0, true), 0x04034b50);
const text = new TextDecoder().decode(bytes);
assert.ok(text.includes('João &amp; Ana'));
assert.ok(text.includes('=1+1 &lt;teste&gt;'));
assert.ok(!text.includes('<f>'));
assert.ok(text.includes('autoFilter ref="A1:M3"'));
await writeFile(new URL('../excel-validation.xlsx', import.meta.url), bytes);
console.log('OK: demanda, durações, acentos, textos literais, filtros e arquivo XLSX.');

assert.equal(rows[1][12], 'Detalhes com acentos: revisão & teste');
assert.equal(rows[2][12], '');
