import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const code = await readFile(new URL('./assets/value-added.js', import.meta.url), 'utf8');
const { classifyReasons, valueAddedColor, createValueAddedSelect } = await import('data:text/javascript;base64,' + Buffer.from(code).toString('base64'));
const rows = [{ label: 'Reuniões corporativas', value: 100 }, { label: 'Outra', value: 50 }];
const entries = [{ description: 'Reuniões corporativas', value_added: 'VA' }];
assert.equal(classifyReasons(rows, entries)[0].classification, 'VA');
assert.equal(classifyReasons(rows, entries)[1].classification, null);
assert.equal(classifyReasons(rows, [{ ...entries[0], value_added: 'NVA' }])[0].classification, 'NVA');
assert.equal(classifyReasons(rows, [...entries, { ...entries[0], value_added: 'NNVA' }])[0].classification, null);
assert.deepEqual(rows.map(row => row.value), classifyReasons(rows, entries).map(row => row.value));
assert.equal(valueAddedColor('VA'), '#238636');
assert.equal(valueAddedColor('NVA'), '#d93643');
assert.equal(valueAddedColor('NNVA'), '#e07818');
assert.equal(valueAddedColor(null), '#8793a0');
let calls = [], messages = [], refreshed = 0;
const React = { createElement: (type, props, ...children) => ({ type, props, children }), useRef: value => ({ current: value }), useState: value => [value, next => messages.push(next)] };
const Select = createValueAddedSelect(React, { rpc: async (...args) => { calls.push(args); return { error: null }; } });
const tree = Select({ entry: { id: 12, description: 'Reunião', value_added: 'VA' }, catalog: { refresh: async () => refreshed++ }, disabled: false });
await tree.children[0].props.onChange({ target: { value: 'NNVA' } });
assert.deepEqual(calls, [['set_description_value_added', { description_id: '12', classification: 'NNVA' }]]);
assert.equal(refreshed, 1);
assert.ok(messages.includes('Classificação salva.'));
const FailedSelect = createValueAddedSelect(React, { rpc: async () => ({ error: new Error('Permission denied') }) });
messages = [];
await FailedSelect({ entry: { id: '1', description: 'X' }, catalog: { refresh: async () => refreshed++ } }).children[0].props.onChange({ target: { value: 'VA' } });
assert.equal(refreshed, 1);
assert.ok(messages.some(message => typeof message === 'string' && message.includes('Não foi possível salvar')));
console.log('OK: cores, cadastro atual, ausências, ambiguidades, persistência e falhas de permissão.');
